version: '3'
services:
  mysql:
    container_name: app_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=UTF8MB4
    environment:
      MYSQL_DATABASE: gimme
      MYSQL_ROOT_PASSWORD: ppp12345!
      MYSQL_ROOT_HOST: '%'
    volumes:
    - my-db:/var/lib/mysql
    ports:
    - "3306:3306"
    restart: always

#  app:
#    build: .
#    volumes:
#    - .:/apps
#    - ~/.m2:/root/.m2
#    working_dir: /app
#    ports:
#    - 8080:8080
#    command: gradle clean spring-boot:run
#    depends_on:
#    -  app_db
# Names our volume
volumes:
  my-db: