version: '3'
services:
  app_db:
    container_name:  app_db
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: gimme
      MYSQL_ROOT_PASSWORD: ppp12345!
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always

#  app:
#    build: .
#    volumes:
#    - .:/app
#    - ~/.m2:/root/.m2
#    working_dir: /app
#    ports:
#    - 8080:8080
#    command: gradle clean spring-boot:run
#    depends_on:
#    -  app_db